assignments/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
    path("" , views.assignmentshome, name = "assignhome"),
    path("<str:unique_name>/", views.assignmentview, name = "assignmentview"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('postComment', views.postComment, name="postComment"),
    path('', views.blogHome, name='blogHome'),
    path('policy', views.policy, name='policy'),
    path('privacy', views.privacy, name='privacy'),
    path('<str:slug>/', views.blogPost, name='blogPost'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mirchalsirstutorials/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from django.utils.html import format_html

admin.site.site_header  =  "Admin Panel - Mirchal Sir's Tutorials "  
admin.site.site_title  =  "Mirchal Sir's Tutorials"
admin.site.index_title  =  "Mirchal Sir's Tutorials"

handler404 = 'blog.views.custom_404'
handler500 = 'blog.views.custom_500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("courses.urls")),
    path('blog/', include('blog.urls')),
    path('quizzes/', include('quizapp.urls')),
    path('assignments/', include('assignments.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizapp/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

assignments/models.py
from django.db import models
import assignments
from courses.models import Course
from django.utils.html import format_html

# Create your models here.
class Assignment(models.Model):
    unique_name = models.CharField(max_length=250)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    topic = models.CharField(max_length = 250)
    questions = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.topic
    

class Submission(models.Model):
    user = models.CharField(max_length=250)
    file = models.FileField(upload_to = 'media')
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)

    def __str__(self):
        return "Submission by " + self.user
    

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils.html import format_html
class Post(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    views = models.IntegerField(default=0)
    content=models.TextField()
    image = models.ImageField(upload_to='media', default="")

    def __str__(self):
        return self.title + " by " + self.author


class BlogComment(models.Model):
    sno= models.AutoField(primary_key=True)
    comment=models.TextField()
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    parent=models.ForeignKey('self', on_delete=models.CASCADE, null=True )
    timestamp= models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[0:13] + "..." + "by" + " " + self.user.username

# Models for videos

class Video(models.Model):
    sno = models.AutoField(primary_key = True)
    caption = models.CharField(max_length = 100)
    speaker = models.CharField(max_length = 100, default = "")
    video = models.FileField(upload_to= 'media')
    timestamp= models.DateTimeField(default=now)

    def __str__(self):
        return self.caption

courses/models/contact.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.CharField(max_length = 250)
    subject = models.CharField(max_length = 350)
    phone = models.CharField(max_length = 250)
    message = models.TextField()

    def __str__(self):
        return self.name
    

courses/models/course.py
from django.db import models

class Teacher(models.Model):
    name = models.CharField(max_length = 100)
    qualification = models.CharField(max_length=100)
    bio = models.TextField()
    picture = models.ImageField(upload_to = "media")
    facebook = models.URLField(max_length=500, default = "https://facebook.com/")
    instagram = models.URLField(max_length=500, default = "https://instagram.com/")
    gmail = models.URLField(max_length=500, default = "https://gmail.com/")
    twitter = models.URLField(max_length=500, default = "https://twitter.com/")

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length = 50 , null = False)
    instructor = models.ForeignKey(Teacher,  on_delete=models.CASCADE, blank=True, null=True)
    slug = models.CharField(max_length = 50 , null = False , unique = True)
    description = models.CharField(max_length = 200 , null = True)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(null=False , default = 0) 
    active = models.BooleanField(default = False)
    thumbnail = models.ImageField(upload_to = "thumbnail") 
    date = models.DateTimeField(auto_now_add= True) 
    resource = models.FileField(upload_to = "resource")
    length = models.IntegerField(null=False)

    def __str__(self):
        return self.name


class CourseProperty(models.Model):
    description  = models.CharField(max_length = 100 , null = False)
    course = models.ForeignKey(Course , null = False , on_delete=models.CASCADE)

    class Meta : 
        abstract = True


class Tag(CourseProperty):
    pass
    
class Prerequisite(CourseProperty):
    pass

class Learning(CourseProperty):
    pass

assignments/forms.py
from django import forms
from . models import Assignment

class SubmissionForm(forms.Form):
    file = forms.FileField(required=False)
    assignment = forms.ModelChoiceField(queryset=Assignment.objects.all(), widget=forms.Select, required=True)

courses/forms/login_form.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate , login
from django.forms import ValidationError

class LoginForm(AuthenticationForm):
    
    username = forms.EmailField(max_length=50 , required = True , label='Email Address')

    def clean(self):
        email = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = None
        try:
            user = User.objects.get(email = email)
            result = authenticate(username = user.username , password = password)

            if(result is not None):
                return result
            else:
                raise ValidationError("Email or Password invalid")
        except:
            raise ValidationError("Email or Password invalid")
        

assignments/views.py
from django.shortcuts import render, redirect
from .models import Assignment, Submission
from . forms import SubmissionForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
# Create your views here.
def assignmentshome(request):
    assignments  = Assignment.objects.filter(is_active = True)
    context = {'assignments': assignments}
    return render(request, 'assignmentshome.html', context)

def assignmentview(request, unique_name):
    if request.method == "POST":
        form = SubmissionForm(request.POST)
        if form.is_valid():
            user = request.user
            file = form.cleaned_data['file']
            assignment = form.cleaned_data['assignment']
            newsubmission = Submission(user = user, file = file, assignment = assignment)
            already_submitted = Submission.objects.filter(user = user, assignment = assignment )
            if already_submitted:
                return HttpResponse("You Have Already Submitted A Response For the Same Assignment")
            else:
                newsubmission.save()
                return HttpResponse("Thanks Press This Button To Go Home")
    form = SubmissionForm(request.POST)
    assignment = Assignment.objects.filter(unique_name = unique_name).first()
    asslist = Assignment.objects.all()
    context = {'assignment': assignment, 'asslist':asslist, 'form':form}
    return render(request, 'assignment.html', context)

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from .models import BlogComment
from django.contrib import messages
from django.contrib.auth.models import User
from .templatetags import extras
from django.contrib import humanize


def custom_404(request, exception):
    return render(request,'404.html')

def custom_500(request):
    return render(request,'404.html')

def blogHome(request):
    allPosts = Post.objects.all().order_by('-timeStamp')
    popularposts = Post.objects.filter()[0:3]
    context = {'allPosts': allPosts, 'popularPosts':popularposts}
    return render(request, 'blog.html', context)

def blogPost(request, slug):
    post=Post.objects.filter(slug=slug).first()
    post.views = post.views + 1
    post.save()

    comments= BlogComment.objects.filter(post=post, parent=None)
    replies= BlogComment.objects.filter(post=post).exclude(parent=None)
    replyDict={}
    for reply in replies:
        if reply.parent.sno not in replyDict.keys():
            replyDict[reply.parent.sno]=[reply]
        else:
            replyDict[reply.parent.sno].append(reply)

    context={'post':post, 'comments': comments, 'user': request.user, 'replyDict': replyDict}
    return render(request, "blogpost.html", context)


def postComment(request):
    if request.method == "POST":
        comment = request.POST.get('comment')
        user = request.user
        postSno = request.POST.get('postSno')
        post = Post.objects.get(sno=postSno)
        parentSno = request.POST.get('parentSno')
        if parentSno == "":
            comment = BlogComment(comment=comment, user=user, post=post)
            comment.save()
            messages.success(request, "Your comment has been posted successfully")
        else:
            parent = BlogComment.objects.get(sno=parentSno)
            comment = BlogComment(comment=comment, user=user, post=post, parent=parent)
            comment.save()
            messages.success(request, "Your reply has been posted successfully")

    return redirect(f"/blog/{post.slug}")

def privacy(request):
    return render(request, 'privacy.html')

def policy(request):
    return render(request, 'policy.html')

courses/views/checkout.py
from django.shortcuts import render , redirect
from courses.models import Course , Video , Payment , UserCourse, video
from django.shortcuts import HttpResponse
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from mirchalsirstutorials.settings import *
from time import time

import razorpay
client = razorpay.Client(auth=('rzp_live_ZsFxLj7hoMk3Xv', 'd8doxHvHbQRmBk0EeX5nljc7'))


@login_required(login_url='/login')
def checkout(request , slug):
    course = Course.objects.get(slug  = slug)
    videos = course.video_set.all().order_by("serial_number")
    user = request.user
    action = request.GET.get('action')
    order = None
    payment = None
    error = None
    try:
        user_course = UserCourse.objects.get(user = user  , course = course)
        error = "You are Already Enrolled in this Course"
    except:
        pass
    amount=None
    if error is None : 
        amount =  int((course.price - ( course.price * course.discount * 0.01 )) * 100)
   # if ammount is zero dont create paymenty , only save emrollment obbect 
    
    if amount==0:
        userCourse = UserCourse(user = user , course = course)
        userCourse.save()
        return redirect('my-courses')   
                # enroll direct
    if action == 'create_payment':

            currency = "INR"
            notes = {
                "email" : user.email, 
                "name" : f'{user.first_name} {user.last_name}'
            }
            reciept = f"codewithvirendra-{int(time())}"
            order = client.order.create(
                {'receipt' :reciept , 
                'notes' : notes , 
                'amount' : amount ,
                'currency' : currency
                }
            )

            payment = Payment()
            payment.user  = user
            payment.course = course
            payment.order_id = order.get('id')
            payment.save()


    
    context = {
        "course" : course , 
        "order" : order, 
        "payment" : payment, 
        "user" : user , 
        "videos":videos,
        "error" : error
    }
    return  render(request , template_name="check_out.html" , context=context )    

@login_required(login_url='/login')
@csrf_exempt
def verifyPayment(request):
    if request.method == "POST":
        data = request.POST
        context = {}
        print(data)
        try:
            client.utility.verify_payment_signature(data)
            razorpay_order_id = data['razorpay_order_id']
            razorpay_payment_id = data['razorpay_payment_id']

            payment = Payment.objects.get(order_id = razorpay_order_id)
            payment.payment_id  = razorpay_payment_id
            payment.status =  True
            
            userCourse = UserCourse(user = payment.user , course = payment.course)
            userCourse.save()

            print("UserCourse" ,  userCourse.id)

            payment.user_course = userCourse
            payment.save()

            return redirect('my-courses')   

        except:
            return HttpResponse("Invalid Payment Details")
        
        
 

courses/views/courses.py
from django.shortcuts import render , redirect
from courses.models import Course , Video , UserCourse
from django.shortcuts import HttpResponse
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.utils.decorators import method_decorator


@method_decorator(login_required(login_url='login') , name='dispatch')
class MyCoursesList(ListView):
    template_name = 'my_courses.html'
    context_object_name = 'user_courses'
    def get_queryset(self):
        return UserCourse.objects.filter(user = self.request.user)


def coursePage(request , slug):
    course = Course.objects.get(slug  = slug)
    serial_number  = request.GET.get('lecture')
    videos = course.video_set.all().order_by("serial_number")

    if serial_number is None:
        serial_number = 1 

    video = Video.objects.get(serial_number = serial_number , course = course)

    if (video.is_preview is False):

        if request.user.is_authenticated is False:
            return redirect("login")
        else:
            user = request.user
            try:
                user_course = UserCourse.objects.get(user = user  , course = course)
            except:
                return redirect("check-out" , slug=course.slug)
        
        
    context = {
        "course" : course , 
        "video" : video , 
        'videos':videos
    }
    return  render(request , template_name="course_page.html" , context=context )  
    

templates/assignment.html
{% extends "basic.html" %} 
{% load static %} 
{% block title %} {{assignment.unique_name}} {% endblock title %} 
{% block js %}
{% comment %} <script>
    $(document).ready(function(){
        var myButton = $('#submitbutton');
        myButton.on('click', function(){
            myButton.prop('disabled', true);
        });
    });
</script> {% endcomment %}
{% endblock js %}


{% block body %}
<section id="contact-page" class="pt-90 pb-120 gray-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="contact-from">
                    <div class="section-title">
                        <h5>Hi</a>, {{request.user}}</h5>
                        <h2>{{assignment.unique_name}}</h2>
                        <h4 class="my-4" style="color: #ffc600;">Topic: {{assignment.topic}}</h4>
                        <div class="container">
                            <h2>{{assignment.questions|linebreaks}}</h2>
                        </div>
                    </div>
                    <!-- section title -->
                </div>
                <!--  login from -->
            </div>
            <div class="col-lg-4">
                <div class="contact-address">
                    <div class="contact-heading">
                        <h5>Submit Your Responses Here</h5>
                        <p>If you face any issues while submitting, please don’t hesitate to contact us.</p>
                    </div>
                    <div class="main-form pt-45">
                        <form action="/assignments/{{assignment.unique_name}}/" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button id = "submitbutton" class = "main-btn mx-2" type="submit" value="Submit">Submit </button>
                        </form>
                    </div>
                </div>
                <!-- contact address -->
            </div>
        </div>
    </div>

</section>
{% endblock body %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        {%block title%}
    {% endblock %}
    </title>
    
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'courses/css/common.css'%}">
    {% block css %} 
    {% endblock %} <title>Hello, world!</title>
  </head>
  <body>
       
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
         

            <!-- right -->

            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                
              </ul>

            <!-- left -->
            <ul class="navbar-nav ml-auto">
              
              {% if request.user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link" href="/my-courses">My Courses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>

              {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Signup</a>
            </li>

            {% endif %}
            
          </ul>
        </div>
      </nav>


    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
      
{% block js %}
{% endblock %}
  
  </body>
</html>

templates/contact.html
{% extends 'basic.html' %}
{% load static %}
{% block title %}Contact Us{% endblock title %}
{% block body %}
    <!--====== PAGE BANNER PART START ======-->
    <section id="page-banner" class="pt-105 pb-130 bg_cover" data-overlay="8" style="background-image: url(/static/courses/images2/page-banner-6.jpg)">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-banner-cont">
                        <h2>Contact</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Contact</li>
                            </ol>
                        </nav>
                    </div>  <!-- page banner cont -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    <!--====== PAGE BANNER PART ENDS ======-->
    <!--====== CONTACT PART START ======-->
    <section id="contact-page" class="pt-90 pb-120 gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="contact-from mt-30">
                        <div class="section-title">
                            <h5>Contact Us</h5>
                            <h2>Keep in touch</h2>
                            <h2></h2>
                        </div> <!-- section title -->
                        <div class="main-form pt-45">
                            <form id="contact-form" action="/contact" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="name" type="text" placeholder="Your name" data-error="Name is required." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="email" type="email" placeholder="Email" data-error="Valid email is required." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="subject" type="text" placeholder="Subject" data-error="Subject is required." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form --> 
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="phone" type="text" placeholder="Phone" data-error="Phone is required." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-12">
                                        <div class="singel-form form-group">
                                            <textarea name="message" placeholder="Message" data-error="Please,leave us a message." required="required"></textarea>
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <p>{% for m in messages %}
                                        {{m}}
                                        {% endfor %}
                                    </p>
                                    <div class="col-md-12">
                                        <div class="singel-form">
                                            <button type="submit" class="main-btn">Send</button>
                                        </div> <!-- singel form -->
                                    </div> 
                                </div> <!-- row -->
                            </form>
                        </div> <!-- main form -->
                    </div> <!--  contact from -->
                </div>
                <div class="col-lg-5">
                    <div class="contact-address mt-30">
                        <ul>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="fa fa-home"></i>
                                    </div>
                                    <div class="cont">
                                        <p>Mirchal Sir's Tutorials, New Colony Sopore.</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="fa fa-phone"></i>
                                    </div>
                                    <div class="cont">
                                        <p>+91 123 456 789</p>
                                        <p>+91 222 345 342</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="fa fa-envelope-o"></i>
                                    </div>
                                    <div class="cont">
                                        <p>info@mirchalsirstutorials.com</p>
                                        <p>queries@mirchalsirstutorials.com</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                        </ul>
                    </div> <!-- contact address -->
                    <div class="map mt-30">
                        <div id="contact-map"></div>
                    </div> <!-- map -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    
    <!--====== CONTACT PART ENDS ======-->
    {% endblock body %}
   

templates/home.html
{% extends 'courses/base.html' %}
{% load course_custom_tags %}
{%block title%}Courses
{% endblock %}

{%block content%}

<style>
    .price {
        font-size: 20px;
    }
</style>

<div class="container">
    <br>
    <div class="row">
        {% for course in allcourses %}
        <div class="col mx-auto">
            <div class="card mx-auto" style="width: 18rem;">
                <img class="card-img-top" src="{{course.thumbnail.url}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{course.name}}</h5>
                    <p class="card-text m-0 p-0">
                        Save {{course.discount}}%
                        <br>
                        <span class="price">
                            <del>{{course.price|rupee}}</del>
                            &nbsp;

                            <span>{% cal_sellprice course.price course.discount as value %} {{value|rupee}}</span>
                        </span>

                    </p>
                </div>

                <div class="card-footer p-0">
                    {% is_enrolled request course as enrolled %}


                    <div class="row no-gutters">
                        {% if enrolled %}
                        <div class="col border-right">
                            <a href="/course/{{course.slug}}" class="btn btn-light btn-block">Start Course</a>
                        </div>
                        {% else %}
                        <div class="col border-right">
                            <a href="/check-out/{{course.slug}}" class="btn btn-light btn-block">Enroll Now</a>
                        </div>
                        <div class="col">
                            <a href="/course/{{course.slug}}" class="btn btn-light  btn-block">Show More</a>
                        </div>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{%endblock%}

templates/privacy.html
{% extends 'basic.html' %}
{% load static %}
{% block title %}
Privacy Policy
{% endblock title %}

{% block body %}
<div class = "container">
    <h3 style = "font-weight: 600;
    font-size: 2 rem;
    color: #07294d;
    text-transform: uppercase;"> Privacy Policy</h3>
    <hr>
    <p>All the details submitted by the user, including name and email shall remain confidential and secure.
        Since we are accepting in-app payments, the payment gateway too is very secure and all your banking information is never stored on the site or by the payment gateway
    </p><br>
</div>
{% endblock body %}

templates/quiz.html
{% extends "basic.html" %}
{% load static %}

{% block js %}
    <script src="/static/courses/js2/quiz.js" defer></script> 
{% endblock js %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block body %}
<div class = "container">
<div id="score-box"></div>
<div id="result-box"></div>
<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>Score to Pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="main-btn btn-danger">Go Back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="main-btn">Save</button>
</form>
</div>
{% endblock body %}